# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'takeumbrella' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for takeumbrella
  pod 'SnapKit'
  pod 'Alamofire'  

  pod 'NMapsMap' # Naver Map API

  target 'takeumbrellaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'takeumbrellaUITests' do
    # Pods for testing
  end

end
